---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-microservice-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: first-microservice
  template:
    metadata:
      labels:
        app: first-microservice
    spec:
      containers:
      - name: first-microservice
        image: your-first-microservice-image  # Replace with your image
        ports:
        - containerPort: 80  # Replace with your port if needed
---
apiVersion: v1
kind: Service
metadata:
  name: first-microservice-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: first-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-microservice-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: second-microservice
  template:
    metadata:
      labels:
        app: second-microservice
    spec:
      containers:
      - name: second-microservice
        image: your-second-microservice-image  # Replace with your image
        ports:
        - containerPort: 80  # Replace with your port if needed
---
apiVersion: v1
kind: Service
metadata:
  name: second-microservice-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: second-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
